spring:
  application:
    name: api-server
  profiles:
    active: prod
  elasticsearch:
    uris: http://s4.java21.net:9200
    username: elastic
    password: nhnacademy123!
    ssl:
      verification-mode: none
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  session:
    redis:
      flush-mode: on_save

  cache:
    type: redis
    redis:
      time-to-live: 600000

  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false  # 예외 시 DLQ로

        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000

  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 10
      max-total: 30
      min-idle: 5
      max-idle: 15
      max-wait: 10000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs: 5000
      min-evictable-idle-time: 60000
      remove-abandoned-on-borrow: true
      remove-abandoned-timeout: 60


aladin:
  base-url: https://www.aladin.co.kr/ttb/api
  ttb-key: ttbtvsqyfzvpj1722001
  output: js
  version: "20131101"

springdoc:
  api-docs:
    path: /bookscamp
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

google:
  gemini:
    ##api-key : AIzaSyCuInq-Nb07tuFDZeK4yLNkTdyZIgsM5Q8  한정키
    api-key : AIzaSyBPqaTSQWhG4sRLVcTfk6v5VvC_Goyjobc