server:
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10351/eureka/

spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be11_team3
    username: project_be11_team3
    password: ${PASSWORD}
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 333
  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: ${RABBITMQ_PASSWORD}
