spring:
  application:
    name: api-server
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  session:
    redis:
      flush-mode: on_save
  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false  # 예외 시 DLQ로

        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000

aladin:
  base-url: https://www.aladin.co.kr/ttb/api
  ttb-key: ttbtvsqyfzvpj1722001
  output: js
  version: "20131101"

springdoc:
  api-docs:
    path: /bookscamp
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

