spring:
  application:
    name: api-server
  profiles:
    active: dev

  config:
    import: "optional:configserver:"   # ★ 이 줄 추가 (포인트)

  cloud:
    config:
      uri: http://localhost:10355      # config-server 주소/포트
      profile: ${spring.profiles.active}
      label: main
      fail-fast: true
