spring:
  application:
    name: api-server
  profiles:
    active: prod

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:10355      # config-server 주소/포트
      profile: ${spring.profiles.active}
      label: main
      fail-fast: true
